import type { Role } from '../types'

/** Reverse-chronological. `featured` roles render expanded; the rest sit behind the disclosure. */
export const experience: readonly Role[] = [
  {
    id: 'nordsecurity-em',
    role: 'Engineering Manager',
    org: 'Nord Security',
    start: '2026-01',
    end: null,
    summary:
      'Leading a team of 8–11 engineers (backend, web, Android, iOS) and 3 QAs across manual and automation, on NordPass.',
    highlights: [
      '1:1s, goal setting, mentoring and coaching across a cross-platform team.',
      'Own effective processes, delegation and technical direction — RFCs, ADRs and PoCs.',
      'Coordinate with 11 other teams inside NordPass.',
      'Second in line after customer support when a client hits a problem.',
    ],
    tech: ['PHP', 'Kotlin', 'Swift', 'AWS', 'Nexos', 'Cursor', 'Claude Code'],
    featured: true,
  },
  {
    id: 'oag-lead',
    role: 'Software Engineering Team Lead',
    org: 'OAG',
    start: '2023-10',
    end: '2025-12',
    summary:
      'Led 4 developers and 2 testers on a message streaming platform pushing flight status and schedule updates — a new product already handling 100M updates daily.',
    highlights: [
      'Reduced incident count by 90% and halved route-to-live time.',
      'Served as interim Product Owner for a year, on top of leading and Scrum Mastering.',
      'Maintained and modernised legacy systems while contributing hands-on as a developer.',
      'Started "Share Learn Grow" sessions and facilitated Coding Dojo to get teams learning from each other.',
    ],
    tech: ['C#', 'Java', 'Azure', 'Terraform', 'Snowflake', 'DataDog', 'SonarCloud', 'CI/CD'],
    featured: true,
  },
  {
    id: 'bpb-writer',
    role: 'Writer',
    org: 'BPB Publications',
    start: '2023-08',
    end: '2024-12',
    summary:
      'Sole author of "Software Craftsmanship using AI" — how classical best practices hold up, and where they have to change, once AI is writing code with you.',
    highlights: [],
    tech: ['Technical writing'],
    featured: true,
  },
  {
    id: 'transunion-principal',
    role: 'Principal Software Engineer',
    org: 'TransUnion',
    start: '2022-09',
    end: '2023-10',
    summary:
      'Tech lead and Scrum Master across microservices for credit scores and the suggestions that help people improve them.',
    highlights: [
      'Recruited two teams — 4 programmers and 2 testers.',
      'Ran the internship process end to end: interviews, team leading, acting as their PO.',
      'Organised cross-team Coding Dojo sessions.',
    ],
    tech: ['C#', 'Microservices', 'Azure', 'BDD', 'SonarQube', 'Fortify', 'Octopus', 'SQL', 'CI/CD'],
    featured: true,
  },
  {
    id: 'transunion-senior',
    role: 'Senior Software Engineer',
    org: 'TransUnion',
    start: '2021-02',
    end: '2022-09',
    summary: 'Breaking a monolith down into microservices.',
    highlights: [],
    tech: ['C#', 'Service Fabric', 'CI/CD'],
    featured: false,
  },
  {
    id: 'packt-author',
    role: 'Author',
    org: 'Packt',
    start: '2020-11',
    end: '2022-09',
    summary:
      'Co-authored "The C# Workshop", writing 5 of its 10 chapters — C#, git, Azure and testing fundamentals.',
    highlights: [],
    tech: ['Technical writing', 'C#'],
    featured: false,
  },
  {
    id: 'sda-teacher',
    role: 'Teacher',
    org: 'Software Development Academy',
    start: '2020-07',
    end: '2021-11',
    summary: 'Helping career changers make the transition into programming.',
    highlights: [],
    tech: ['C#', 'Teaching'],
    featured: false,
  },
  {
    id: 'transunion-swe',
    role: 'Software Engineer',
    org: 'TransUnion',
    start: '2019-10',
    end: '2021-02',
    summary:
      'Built Open Banking solutions — new microservices and maintenance of existing ones: GDPR data filter, financial transactions, banks, orchestrator.',
    highlights: [],
    tech: ['C#', 'Service Fabric', 'Azure', 'Octopus', 'SQL', 'git', 'CI/CD'],
    featured: false,
  },
  {
    id: 'kaunas-coding-school',
    role: 'Teacher',
    org: 'Kaunas Coding School',
    start: '2019-03',
    end: '2019-07',
    summary:
      'Taught another company’s junior programmers C#, clean code, design patterns, unit testing and an introduction to microservices.',
    highlights: [],
    tech: ['C#', 'Teaching'],
    featured: false,
  },
  {
    id: 'present-connection',
    role: '.NET Developer',
    org: 'Present Connection',
    start: '2017-10',
    end: '2019-10',
    summary:
      'Web services and Exact plugins — including an abstraction library that made the Exact integration unit-testable.',
    highlights: [],
    tech: ['.NET', 'C#', 'WCF', 'WinForms', 'WebForms', 'PHP', 'MSSQL', 'svn', 'tfs'],
    featured: false,
  },
  {
    id: 'sneakybox',
    role: 'Game Developer',
    org: 'SneakyBox',
    start: '2016-12',
    end: '2017-08',
    summary:
      'Worked alongside a game designer and an artist, programming for Android and iOS.',
    highlights: [],
    tech: ['Unity', 'C#', 'Android Studio', 'Google Play Services'],
    featured: false,
  },
]
