import type { Role } from '../types'

/** Kompanijų pavadinimai ir technologijos neverčiami. */
export const experience: readonly Role[] = [
  {
    id: 'nordsecurity-em',
    role: 'Inžinerijos vadovas',
    org: 'Nord Security',
    start: '2026-01',
    end: null,
    summary:
      'Vadovauju 8–11 programuotojų (backend, web, Android, iOS) ir 3 testuotojų komandai — rankinis ir automatinis testavimas — dirbančiai prie NordPass.',
    highlights: [
      '1:1 pokalbiai, tikslų kėlimas, mentorystė ir koučingas kelių platformų komandoje.',
      'Atsakingas už efektyvius procesus, darbų paskirstymą ir techninę kryptį — RFC, ADR, PoC.',
      'Koordinacija su 11 kitų NordPass komandų.',
      'Antra grandis po klientų aptarnavimo, kai klientas susiduria su problema.',
    ],
    tech: ['PHP', 'Kotlin', 'Swift', 'AWS', 'Nexos', 'Cursor', 'Claude Code'],
    featured: true,
  },
  {
    id: 'oag-lead',
    role: 'Programuotojų komandos vadovas',
    org: 'OAG',
    start: '2023-10',
    end: '2025-12',
    summary:
      'Vadovavau 4 programuotojų ir 2 testuotojų komandai, kūrusiai pranešimų srautų platformą skrydžių statusams ir tvarkaraščiams siųsti — naujas produktas, jau apdorojantis 100 mln. atnaujinimų per parą.',
    highlights: [
      'Sumažinau incidentų skaičių 90 % ir perpus sutrumpinau kelią iki produkcijos.',
      'Metus ėjau laikino produkto savininko pareigas greta vadovavimo ir Scrum Master vaidmens.',
      'Palaikiau ir modernizavau legacy sistemas, kartu pats programuodamas.',
      'Pradėjau „Share Learn Grow“ sesijas ir vedžiau Coding Dojo, kad komandos mokytųsi vienos iš kitų.',
    ],
    tech: ['C#', 'Java', 'Azure', 'Terraform', 'Snowflake', 'DataDog', 'SonarCloud', 'CI/CD'],
    featured: true,
  },
  {
    id: 'bpb-writer',
    role: 'Rašytojas',
    org: 'BPB Publications',
    start: '2023-08',
    end: '2024-12',
    summary:
      'Knygos „Software Craftsmanship using AI“ autorius — kaip klasikinės geros praktikos laikosi ir kur joms tenka keistis, kai kodą rašai kartu su dirbtiniu intelektu.',
    highlights: [],
    tech: ['Techninis rašymas'],
    featured: true,
  },
  {
    id: 'transunion-principal',
    role: 'Vyriausiasis programuotojas',
    org: 'TransUnion',
    start: '2022-09',
    end: '2023-10',
    summary:
      'Techninis vadovas ir Scrum Master mikroservisuose, skirtuose kreditingumo įvertinimams ir patarimams, kaip juos pagerinti.',
    highlights: [
      'Subūriau dvi komandas — 4 programuotojus ir 2 testuotojus.',
      'Vedžiau visą praktikos procesą: interviu, vadovavimą praktikantams, jų produkto savininko vaidmenį.',
      'Organizavau tarpkomandines Coding Dojo sesijas.',
    ],
    tech: ['C#', 'Mikroservisai', 'Azure', 'BDD', 'SonarQube', 'Fortify', 'Octopus', 'SQL', 'CI/CD'],
    featured: true,
  },
  {
    id: 'transunion-senior',
    role: 'Vyresnysis programuotojas',
    org: 'TransUnion',
    start: '2021-02',
    end: '2022-09',
    summary: 'Monolito skaidymas į mikroservisus.',
    highlights: [],
    tech: ['C#', 'Service Fabric', 'CI/CD'],
    featured: false,
  },
  {
    id: 'packt-author',
    role: 'Autorius',
    org: 'Packt',
    start: '2020-11',
    end: '2022-09',
    summary:
      'Knygos „The C# Workshop“ bendraautoris — parašiau 5 iš 10 skyrių apie C#, git, Azure ir testavimo pagrindus.',
    highlights: [],
    tech: ['Techninis rašymas', 'C#'],
    featured: false,
  },
  {
    id: 'sda-teacher',
    role: 'Mokytojas',
    org: 'Software Development Academy',
    start: '2020-07',
    end: '2021-11',
    summary: 'Padėjau karjerą keičiantiems žmonėms pereiti į programavimą.',
    highlights: [],
    tech: ['C#', 'Mokymas'],
    featured: false,
  },
  {
    id: 'transunion-swe',
    role: 'Programuotojas',
    org: 'TransUnion',
    start: '2019-10',
    end: '2021-02',
    summary:
      'Kūriau „Open Banking“ sprendimus — naujus mikroservisus ir palaikiau esamus: GDPR duomenų filtras, finansinės transakcijos, bankai, orkestratorius.',
    highlights: [],
    tech: ['C#', 'Service Fabric', 'Azure', 'Octopus', 'SQL', 'git', 'CI/CD'],
    featured: false,
  },
  {
    id: 'kaunas-coding-school',
    role: 'Mokytojas',
    org: 'Kaunas Coding School',
    start: '2019-03',
    end: '2019-07',
    summary:
      'Mokiau kitos įmonės jaunesniuosius programuotojus C#, švaraus kodo, projektavimo šablonų, vienetų testavimo ir mikroservisų pagrindų.',
    highlights: [],
    tech: ['C#', 'Mokymas'],
    featured: false,
  },
  {
    id: 'present-connection',
    role: '.NET programuotojas',
    org: 'Present Connection',
    start: '2017-10',
    end: '2019-10',
    summary:
      'Web servisai ir Exact įskiepiai — įskaitant abstrakcijų biblioteką, leidusią Exact integraciją padengti vienetų testais.',
    highlights: [],
    tech: ['.NET', 'C#', 'WCF', 'WinForms', 'WebForms', 'PHP', 'MSSQL', 'svn', 'tfs'],
    featured: false,
  },
  {
    id: 'sneakybox',
    role: 'Žaidimų programuotojas',
    org: 'SneakyBox',
    start: '2016-12',
    end: '2017-08',
    summary:
      'Dirbau kartu su žaidimų dizaineriu ir dailininke, programavau Android ir iOS platformoms.',
    highlights: [],
    tech: ['Unity', 'C#', 'Android Studio', 'Google Play Services'],
    featured: false,
  },
]
